- name: Audit SNMP
  hosts: all
  gather_facts: no

  tasks:
    - name: Vérifier si SNMP est configuré
      cisco.ios.ios_facts:
        gather_subset: config
      register: config

    - name: Échec si SNMP absent
      fail:
        msg: "SNMP n'est pas configuré sur {{ inventory_hostname }}"
      when: "'snmp-server' not in config.ansible_facts.ansible_net_config"
