- hosts: all
  gather_facts: false
  tasks:  
  - name: Ecrire les facts reseau dans un fichier
    cisco.ios.ios_facts:
      gather_subset:
      - "!all"
    register: ios_facts
  - name: Sauvegarder les facts reseau dans un fichier JSON
    ansible.builtin.copy:
      content: "{{ ios_facts.ansible_facts| to_nice_json }}"
      dest: "./facts/facts_{{ inventory_hostname }}.json"